# Generated by Django 5.0.6 on 2024-07-07 08:13

import django.core.validators
import phones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название телефона')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('image', models.ImageField(upload_to=phones.models.phone_cover_image_path, verbose_name='Обложка телефона')),
                ('release_date', models.DateField(verbose_name='release_date')),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефон',
            },
        ),
    ]
